use serde::{Deserialize,Serialize};use std::{path::{Path,PathBuf},process::Stdio,sync::{Arc,Mutex}};use tauri::State;
#[derive(Default,Clone)]struct AppState{roots:Arc<Mutex<Vec<PathBuf>>>}
#[derive(Serialize)]struct MediaInfo{title:String,thumbnail:Option<String>,duration:Option<String>}
#[derive(Deserialize)]struct DownloadRequest{url:String,destination:PathBuf,filename:String,format:String,quality:String}
fn canonical(p:&Path)->Result<PathBuf,String>{std::fs::canonicalize(p).map_err(|e|e.to_string())}fn allowed(state:&AppState,p:&Path)->Result<PathBuf,String>{let p=canonical(p)?;let roots=state.roots.lock().map_err(|_|"root lock failed")?;if roots.iter().any(|r|p.starts_with(r)){Ok(p)}else{Err("Path is outside authorized DownTrack locations".into())}}
#[tauri::command]fn set_authorized_roots(state:State<AppState>,roots:Vec<String>)->Result<Vec<String>,String>{let mut g=state.roots.lock().map_err(|_|"root lock failed")?;let mut out=Vec::new();for r in roots{let p=canonical(Path::new(&r))?;if p.is_dir(){out.push(p.clone());}}*g=out.clone();Ok(out.into_iter().map(|p|p.to_string_lossy().to_string()).collect())}
#[tauri::command]fn authorized_roots(state:State<AppState>)->Result<Vec<String>,String>{let g=state.roots.lock().map_err(|_|"root lock failed")?;Ok(g.iter().map(|p|p.to_string_lossy().to_string()).collect())}
#[tauri::command]fn list_directory(state:State<AppState>,path:String)->Result<Vec<String>,String>{let d=allowed(&state,Path::new(&path))?;Ok(std::fs::read_dir(d).map_err(|e|e.to_string())?.filter_map(|e|e.ok()).map(|e|e.path().to_string_lossy().to_string()).collect())}
#[tauri::command]async fn inspect_media(url:String)->Result<MediaInfo,String>{let o=tokio::process::Command::new("yt-dlp").args(["--dump-single-json","--no-playlist",&url]).stdout(Stdio::piped()).stderr(Stdio::null()).output().await.map_err(|e|e.to_string())?;if !o.status.success(){return Err("Unable to inspect media".into())}let v:serde_json::Value=serde_json::from_slice(&o.stdout).map_err(|e|e.to_string())?;Ok(MediaInfo{title:v.get("title").and_then(|x|x.as_str()).unwrap_or("Untitled").into(),thumbnail:v.get("thumbnail").and_then(|x|x.as_str()).map(String::from),duration:v.get("duration_string").and_then(|x|x.as_str()).map(String::from)})}
#[tauri::command]async fn start_download(state:State<'_,AppState>,req:DownloadRequest)->Result<(),String>{let d=allowed(&state,&req.destination)?;tokio::fs::create_dir_all(&d).await.map_err(|e|e.to_string())?;let out=d.join(req.filename).to_string_lossy().to_string();let selector=if req.format.eq_ignore_ascii_case("mp3"){"bestaudio/best".into()}else{format!("bestvideo[height<={}] + bestaudio/best",req.quality.trim_end_matches('p'))};let s=tokio::process::Command::new("yt-dlp").args(["--newline","--no-playlist","-f",&selector,"--merge-output-format",&req.format,"-o",&out,&req.url]).stdout(Stdio::null()).stderr(Stdio::null()).status().await.map_err(|e|e.to_string())?;if s.success(){Ok(())}else{Err("Download failed".into())}}
fn main(){tauri::Builder::default().manage(AppState::default()).invoke_handler(tauri::generate_handler![set_authorized_roots,authorized_roots,list_directory,inspect_media,start_download]).run(tauri::generate_context!()).expect("DownTrack failed to start")}
