import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{invoke}from'@tauri-apps/api/core';
import{listen,UnlistenFn}from'@tauri-apps/api/event';
import{Folder,FolderPlus,Download,Settings,Search,Grid2X2,List,Plus,ChevronRight,Home,Music,Film,ShieldCheck,Pause,Play,X,Check,Globe2,LockKeyhole,MoreVertical,RefreshCw,Sun,Moon,File,ArrowUp,Trash2,Copy,Scissors,PenLine}from'lucide-react';
import'./styles.css';
import{LOCALES,localeList}from'./i18n';
import type{LocaleCode}from'./i18n';

type Root={id:string;name:string;path:string};
type Entry={name:string;path:string;is_dir:boolean;size:number;extension?:string|null};
type Job={id:number;name:string;type:string;progress:number;speed:string;eta:string;status:'downloading'|'done'|'paused'|'error'|'canceled';url:string;destination:string;filename:string;format:string;quality:string;embedMetadata:boolean;embedThumbnail:boolean;subtitles:boolean;createdAt:number};
type Strings=Record<string,string>;
type MediaInfo={title:string;thumbnail?:string|null;duration?:string|null;uploader?:string|null;qualities:number[]};

const formatBytes=(n:number)=>n>=1e9?(n/1e9).toFixed(2)+' GB':n>=1e6?(n/1e6).toFixed(1)+' MB':n>=1e3?(n/1e3).toFixed(1)+' KB':n+' B';
const mediaExts=new Set(['mp4','mkv','webm','mov','avi','m4v','flv','wmv']);

const entryIcon=(e:Entry)=><>{e.is_dir?<Folder/>:e.extension?.toLowerCase()==='mp3'?<Music/>:mediaExts.has(e.extension?.toLowerCase()||'')?<Film/>:<File/>}</>;

function App(){
 const[theme,setTheme]=useState<'dark'|'light'>(()=>{try{return(localStorage.getItem('downtrack-theme')as 'dark'|'light')||'dark'}catch{return'dark'}});const[concurrency,setConcurrency]=useState<number>(()=>{try{return Number(localStorage.getItem('downtrack-concurrency'))||3}catch{return 3}});
 const[language,setLanguage]=useState<LocaleCode>(()=>{try{const v=localStorage.getItem('downtrack-language')as LocaleCode;return v&&LOCALES[v]?v:'en'}catch{return'en'}});
 const t=LOCALES[language].strings;
 const direction=LOCALES[language].dir;
 const[roots,setRoots]=useState<Root[]>([]),[currentPath,setCurrentPath]=useState(''),[entries,setEntries]=useState<Entry[]>([]);
 const[view,setView]=useState<'grid'|'list'>('grid'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true);
 const[add,setAdd]=useState(false),[prefillUrl,setPrefillUrl]=useState(''),[dropActive,setDropActive]=useState(false),[settings,setSettings]=useState(false),[downloadsOpen,setDownloadsOpen]=useState(false),[error,setError]=useState('');
 const[jobs,setJobs]=useState<Job[]>(()=>{try{const saved=JSON.parse(localStorage.getItem('downtrack-jobs')||'[]')as Job[];return Array.isArray(saved)?saved.map(j=>j.status==='downloading'?{...j,status:'paused'}:j):[]}catch{return[]}});
 const[selected,setSelected]=useState<Entry|null>(null);
 const[currentRoot]=useState<Root|undefined>(undefined);

 const applyTheme=(next:'dark'|'light')=>{setTheme(next);try{localStorage.setItem('downtrack-theme',next)}catch{}};
 const applyLanguage=(next:LocaleCode)=>{setLanguage(next);try{localStorage.setItem('downtrack-language',next)}catch{}};

 const rootForPath=useMemo(()=>roots.find(r=>currentPath===r.path||currentPath.startsWith(r.path+'\\')||currentPath.startsWith(r.path+'/')),[roots,currentPath]);
 const breadcrumbs=useMemo(()=>{if(!rootForPath)return[];if(currentPath===rootForPath.path)return[{name:rootForPath.name,path:rootForPath.path}];const rel=currentPath.slice(rootForPath.path.length).replace(/^[/\\]+/,'');const parts=rel.split(/[/\\]+/).filter(Boolean);let p=rootForPath.path;return[{name:rootForPath.name,path:p},...parts.map(name=>{p=p.replace(/[\\/]$/,'')+'\\'+name;return{name,path:p}})]},[rootForPath,currentPath]);
 const visibleEntries=useMemo(()=>entries.filter(e=>e.name.toLowerCase().includes(query.trim().toLowerCase())),[entries,query]);

 const loadDir=async(path:string)=>{if(!path)return;setLoading(true);setError('');try{setEntries(await invoke<Entry[]>('list_directory',{path}));setCurrentPath(path);setSelected(null)}catch(e){setEntries([]);setError(String(e))}finally{setLoading(false)}};
 const refreshRoots=async()=>{try{const r=await invoke<Root[]>('authorized_roots');setRoots(r);if(!currentPath&&r[0])setCurrentPath(r[0].path);if(currentPath&&!r.some(x=>currentPath===x.path||currentPath.startsWith(x.path+'\\')||currentPath.startsWith(x.path+'/')))setCurrentPath(r[0]?.path||'')}catch(e){setError(String(e))}};
 useEffect(()=>{try{localStorage.setItem('downtrack-jobs',JSON.stringify(jobs))}catch{}},[jobs]);
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=direction},[language,direction]);
 useEffect(()=>{const saved=Math.min(8,Math.max(1,Number(localStorage.getItem('downtrack-concurrency'))||3));setConcurrency(saved);invoke<number>('set_download_concurrency',{maxParallel:saved}).catch(()=>{})},[]);
 useEffect(()=>{let off:UnlistenFn|undefined;refreshRoots().finally(()=>setLoading(false));listen<any>('download-progress',event=>{const e=event.payload as {id:number;status:string;percent:number;speed:string;eta:string;filename:string;message?:string};setJobs(prev=>prev.map(j=>j.id===e.id?{...j,progress:e.percent,speed:e.speed,eta:e.message||e.eta,status:e.status==='completed'?'done':e.status==='paused'?'paused':e.status==='canceled'?'canceled':e.status==='error'?'error':'downloading'}:j))}).then(x=>off=x).catch(()=>{});return()=>{if(off)off()};},[]);
 useEffect(()=>{if(currentPath)loadDir(currentPath)},[currentPath]);

 const addRoot=async()=>{try{const root=await invoke<Root|null>('pick_root');if(root){await refreshRoots();setCurrentPath(root.path)}}catch(e){setError(String(e))}};
 const removeRoot=async(root:Root)=>{if(!confirm(t.remove+'?'))return;try{await invoke('remove_root',{path:root.path});await refreshRoots()}catch(e){setError(String(e))}};
 const newFolder=async()=>{const name=prompt(t.newFolder);if(!name)return;try{await invoke('create_directory',{parent:currentPath,name});await loadDir(currentPath)}catch(e){setError(String(e))}};
 const renameSelected=async()=>{if(!selected)return;const name=prompt(t.rename,selected.name);if(!name||name===selected.name)return;try{await invoke('rename_entry',{path:selected.path,newName:name});await loadDir(currentPath)}catch(e){setError(String(e))}};
 const copySelected=async()=>{if(!selected)return;const dest=prompt(t.destination,currentPath);if(!dest)return;try{await invoke('copy_entry',{source:selected.path,destinationParent:dest});await loadDir(currentPath)}catch(e){setError(String(e))}};
 const moveSelected=async()=>{if(!selected)return;const dest=prompt(t.destination,currentPath);if(!dest)return;try{await invoke('move_entry',{source:selected.path,destinationParent:dest});await loadDir(currentPath)}catch(e){setError(String(e))}};
 const deleteSelected=async()=>{if(!selected)return;if(!confirm(t.delete+' '+selected.name+'?'))return;try{await invoke('delete_entry',{path:selected.path});await loadDir(currentPath)}catch(e){setError(String(e))}};
 const cancelJob=async(j:Job)=>{try{if(j.status==='downloading'||j.status==='paused')await invoke('control_download',{id:j.id,action:'cancel'});setJobs(prev=>prev.map(x=>x.id===j.id?{...x,status:'canceled'}:x))}catch(e){setError(String(e))}};
 const resumeJob=async(j:Job)=>{try{await invoke('resume_download',{req:{url:j.url,destination:j.destination,filename:j.filename,format:j.format,quality:j.quality,embed_metadata:j.embedMetadata,embed_thumbnail:j.embedThumbnail,subtitles:j.subtitles,job_id:j.id,resume:true}});setJobs(prev=>prev.map(x=>x.id===j.id?{...x,status:'downloading',eta:t.resume+'…'}:x))}catch(e){setError(String(e))}};
 const pauseJob=async(j:Job)=>{try{await invoke('control_download',{id:j.id,action:'pause'});setJobs(prev=>prev.map(x=>x.id===j.id?{...x,status:'paused'}:x))}catch(e){setError(String(e))}};
 const retryJob=async(j:Job)=>{try{await invoke('start_download',{req:{url:j.url,destination:j.destination,filename:j.filename,format:j.format,quality:j.quality,embed_metadata:j.embedMetadata,embed_thumbnail:j.embedThumbnail,subtitles:j.subtitles,job_id:j.id,resume:true}});setJobs(prev=>prev.map(x=>x.id===j.id?{...x,status:'downloading',progress:0,eta:t.inspecting,speed:''}:x))}catch(e){setError(String(e))}};
 const controlJob=(j:Job)=>j.status==='paused'?resumeJob(j):pauseJob(j);
 const openEntry=(e:Entry)=>e.is_dir?loadDir(e.path):invoke('open_location',{path:e.path}).catch(e=>setError(String(e)));

 return <div className={'app '+theme+(direction==='ltr'?' ltr':' rtl')} dir={direction}>
 <aside className="sidebar"><div className="brand"><div className="logo">▶</div><div><b>DownTrack</b><span>Media Workspace</span></div></div>
 <div className="section-label">{t.locations}</div>
 <button className="nav active" onClick={()=>roots[0]&&loadDir(roots[0].path)}><Home/>{t.home}</button>
 {roots.map(r=><button key={r.id} className={'nav '+(rootForPath?.id===r.id?'selected':'')} onClick={()=>loadDir(r.path)}><Folder/>{r.name}</button>)}
 <button className="nav" onClick={()=>setDownloadsOpen(true)}><Download/>{t.downloads}<em>{jobs.filter(j=>j.status==='downloading').length}</em></button>
 <div className="side-spacer"/>
 <button className="nav accent" onClick={()=>setAdd(true)}><Plus/>{t.addMedia}</button>
 <button className="nav" onClick={()=>setSettings(true)}><Settings/>{t.settings}</button>
 <div className="secure"><ShieldCheck/><div><b>{t.protected}</b><span>{t.authorizedOnly}</span></div></div></aside>

 <main className={"main "+(dropActive?"drop-active":"")} onDragOver={e=>{e.preventDefault();setDropActive(true)}} onDragLeave={e=>{if(e.currentTarget===e.target)setDropActive(false)}} onDrop={e=>{e.preventDefault();setDropActive(false);const raw=e.dataTransfer.getData('text/uri-list')||e.dataTransfer.getData('text/plain');const url=raw.split('\n')[0].trim();if(/^https?:\/\//i.test(url)){setPrefillUrl(url);setAdd(true)}}}><header><div className="crumbs">{breadcrumbs.map((b,i)=><React.Fragment key={b.path}>{i>0&&<ChevronRight size={15}/>}<button onClick={()=>loadDir(b.path)}>{i===0?<Home size={16}/>:b.name}</button></React.Fragment>)}</div>
 <div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></div>
 <div className="toolbar"><button onClick={()=>setView('grid')} className={view==='grid'?'on':''}><Grid2X2/></button><button onClick={()=>setView('list')} className={view==='list'?'on':''}><List/></button><button onClick={()=>currentPath&&loadDir(currentPath)}><RefreshCw/></button><button className="theme-toggle" onClick={()=>applyTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun/>:<Moon/>}</button></div></header>

 {error&&<div className="error-banner"><span>{error}</span><button onClick={()=>setError('')}><X size={15}/></button></div>}
 {!currentPath&&roots.length===0&&!loading?<EmptyState t={t} onAdd={addRoot}/>:<section className="content">
 <div className="title-row"><div><h1>{rootForPath?.name||t.locations}</h1><p>{currentPath} · {t.includesSubfolders}</p></div><div className="action-row"><button className="secondary top-action" onClick={newFolder}><FolderPlus/>{t.newFolder}</button><button className="primary" onClick={()=>setAdd(true)}><Plus/>{t.addMedia}</button></div></div>
 <div className="file-tools"><button className="up-button" onClick={()=>breadcrumbs.length>1&&loadDir(breadcrumbs[breadcrumbs.length-2].path)} disabled={breadcrumbs.length<=1}><ArrowUp/>{t.up}</button>{selected?<><span className="selected-label">{selected.name}</span><button onClick={renameSelected}><PenLine/>{t.rename}</button><button onClick={deleteSelected}><Trash2/>{t.delete}</button><button onClick={copySelected}><Copy/>{t.copy}</button><button onClick={moveSelected}><Scissors/>{t.move}</button></>:<span>{visibleEntries.length} {t.items}</span>}</div>
 {loading?<div className="loading">{t.loading}</div>:view==='grid'?<div className="file-grid">{visibleEntries.map(e=><article key={e.path} onClick={()=>setSelected(e)} onDoubleClick={()=>openEntry(e)} className={'file-card '+(selected?.path===e.path?'selected-card':'')}><div className={e.is_dir?'folder-icon':'thumb'}>{entryIcon(e)}</div><b title={e.name}>{e.name}</b><span>{e.is_dir?t.folder:(e.extension?.toUpperCase()||t.file)+' · '+formatBytes(e.size)}</span><button className="more" onClick={ev=>{ev.stopPropagation();setSelected(e)}}><MoreVertical/></button></article>)}</div>:<div className="file-list">{visibleEntries.map(e=><button key={e.path} className={'list-row '+(selected?.path===e.path?'selected-row':'')} onClick={()=>setSelected(e)} onDoubleClick={()=>openEntry(e)}><span className="list-icon">{entryIcon(e)}</span><span className="list-name">{e.name}</span><span>{e.is_dir?t.folder:e.extension?.toUpperCase()||t.file}</span><span>{e.is_dir?'—':formatBytes(e.size)}</span></button>)}</div>}
 </section>}
 <div className="downloads-panel"><div className="panel-head"><div><b>{t.activeDownloads}</b><span>{jobs.filter(j=>j.status==='downloading').length} {t.active}</span></div><button onClick={()=>setDownloadsOpen(true)}>{t.showAll}<ChevronRight/></button></div><div className="job-row">{jobs.length===0?<div className="empty-jobs">{t.noDownloads}</div>:jobs.slice(0,4).map(j=><div className="job" key={j.id}><div className="job-icon"><Film/></div><div className="job-info"><b>{j.name}</b><span>{j.type}</span><div className="progress"><i style={{width:j.progress+'%'}}/></div><small>{j.progress}% · {j.speed||'—'} · {j.eta||'—'}</small></div><button onClick={()=>controlJob(j)} disabled={j.status!=='downloading'&&j.status!=='paused'}>{j.status==='paused'?<Play/>:<Pause/>}</button><button onClick={()=>cancelJob(j)}><X/></button></div>)}</div></div>
 </main>
 {add&&<AddMedia t={t} initialUrl={prefillUrl} onClose={()=>{setAdd(false);setPrefillUrl('')}} target={currentPath} onQueued={j=>setJobs(x=>[j,...x])}/>}
 {settings&&<SettingsModal t={t} language={language} setLanguage={applyLanguage} theme={theme} setTheme={applyTheme} concurrency={concurrency} setConcurrency={n=>{setConcurrency(n);localStorage.setItem('downtrack-concurrency',String(n));invoke('set_download_concurrency',{maxParallel:n}).catch(()=>{})}} roots={roots} addRoot={addRoot} removeRoot={removeRoot} onClose={()=>setSettings(false)}/>}
 {downloadsOpen&&<DownloadCenter t={t} jobs={jobs} onClose={()=>setDownloadsOpen(false)} onControl={controlJob} onCancel={cancelJob} onRetry={retryJob} onRemove={id=>setJobs(x=>x.filter(j=>j.id!==id))}/>}
 </div>
}

function EmptyState({t,onAdd}:{t:Strings;onAdd:()=>void}){return <div className="empty-state"><div className="empty-logo"><ShieldCheck/></div><h2>{t.welcome}</h2><p>{t.welcomeText}</p><button className="primary" onClick={onAdd}><FolderPlus/>{t.addLocation}</button><small>{t.locationHint}</small></div>}

function AddMedia({t,initialUrl,onClose,target,onQueued}:{t:Strings;initialUrl:string;onClose:()=>void;target:string;onQueued:(j:Job)=>void}){const[url,setUrl]=useState(initialUrl),[quality,setQuality]=useState('1080p'),[format,setFormat]=useState('MP4'),[name,setName]=useState(''),[embedMetadata,setEmbedMetadata]=useState(true),[embedThumbnail,setEmbedThumbnail]=useState(true),[subtitles,setSubtitles]=useState(false),[info,setInfo]=useState<MediaInfo|null>(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 useEffect(()=>{if(initialUrl)setUrl(initialUrl)},[initialUrl]);
 const inspect=async()=>{if(!url.trim())return;setBusy(true);setErr('');try{const v=await invoke<MediaInfo>('inspect_media',{url:url.trim()});setInfo(v);if(!name)setName(v.title);if(v.qualities?.length){const preferred=Math.max(...v.qualities.filter(q=>q<=1080),Math.max(...v.qualities));setQuality(String(preferred))}}catch{setErr(t.identifyError)}finally{setBusy(false)}};
 const queue=async()=>{if(!url.trim()||!target||!name.trim())return;const filename=name.trim()+'.'+format.toLowerCase();try{const id=await invoke<number>('start_download',{req:{url:url.trim(),destination:target,filename,format,quality,embed_metadata:embedMetadata,embed_thumbnail:embedThumbnail,subtitles}});onQueued({id,name:filename,type:quality+' • '+format,progress:0,speed:'',eta:t.inspecting,status:'downloading',url:url.trim(),destination:target,filename,format,quality,embedMetadata,embedThumbnail,subtitles,createdAt:Date.now()});onClose()}catch{setErr(t.identifyError)}};
 return <div className="overlay"><div className="modal add-modal"><div className="modal-head"><div><h2>{t.addMediaTitle}</h2><span>{t.addMediaHint}</span></div><button onClick={onClose}><X/></button></div><label>{t.link}<input autoFocus value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&inspect()} placeholder={t.link}/></label><button className="inspect-button" onClick={inspect} disabled={busy}>{busy?t.inspecting:t.inspect}</button>{info&&<div className="preview">{info.thumbnail?<img src={info.thumbnail} alt=""/>:<div className="preview-img"><Film/></div>}<div><b>{info.title}</b><span>{info.duration||'Media'} · {t.detected}</span></div><Check/></div>}{err&&<div className="modal-error">{err}</div>}<label>{t.quality}<select value={quality} onChange={e=>setQuality(e.target.value)}>{(info?.qualities?.length?[...info.qualities].sort((a,b)=>b-a):[2160,1440,1080,720,480]).map(q=><option key={q} value={String(q)}>{q}p</option>)}</select></label><div className="formats"><label>{t.format}</label><div>{['MP4','MKV','MP3'].map(x=><button key={x} className={format===x?'picked':''} onClick={()=>setFormat(x)}>{x}</button>)}</div></div><div className="media-options"><label className="check-option"><input type="checkbox" checked={embedMetadata} onChange={e=>setEmbedMetadata(e.target.checked)}/><span>Metadata</span></label><label className="check-option"><input type="checkbox" checked={embedThumbnail} onChange={e=>setEmbedThumbnail(e.target.checked)}/><span>Thumbnail / Cover</span></label><label className="check-option"><input type="checkbox" checked={subtitles} onChange={e=>setSubtitles(e.target.checked)}/><span>Subtitles</span></label></div><label>{t.filename}<input value={name} onChange={e=>setName(e.target.value)} placeholder={t.filename}/></label><div className="destination"><Folder/><div><span>{t.destination}</span><b>{target||t.noLocation}</b></div><Check/></div><button className="primary wide" disabled={!target||!name.trim()||!url.trim()} onClick={queue}><Download/>{t.addToDownloads}</button></div></div>
}

function SettingsModal({t,language,setLanguage,theme,setTheme,concurrency,setConcurrency,roots,addRoot,removeRoot,onClose}:{t:Strings;language:LocaleCode;setLanguage:(l:LocaleCode)=>void;theme:'dark'|'light';setTheme:(t:'dark'|'light')=>void;concurrency:number;setConcurrency:(n:number)=>void;roots:Root[];addRoot:()=>void;removeRoot:(r:Root)=>void;onClose:()=>void}){return <div className="overlay"><div className="modal settings-modal"><div className="modal-head"><div><h2>{t.settings}</h2><span>{t.settingsHint}</span></div><button onClick={onClose}><X/></button></div><div className="settings-grid"><div className="setting active"><Globe2/><div><b>{t.language}</b><select className="language-select" value={language} onChange={e=>setLanguage(e.target.value as LocaleCode)}>{localeList.map(l=><option key={l.code} value={l.code}>{l.name}</option>)}</select></div></div><div className="setting"><Sun/><div><b>{t.style}</b><div className="theme-options"><button className={theme==='dark'?'picked':''} onClick={()=>setTheme('dark')}><Moon/>{t.dark}</button><button className={theme==='light'?'picked':''} onClick={()=>setTheme('light')}><Sun/>{t.light}</button></div></div></div><div className="setting"><LockKeyhole/><div><b>{t.privacy}</b><span>{t.rootsOnly}</span></div></div><div className="setting"><Download/><div><b>{t.downloadSettings}</b><span>{t.downloadSettingsHint}</span><select className="concurrency-select" value={concurrency} onChange={e=>setConcurrency(Number(e.target.value))}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n} concurrent</option>)}</select></div></div></div><div className="roots"><h3>{t.authorizedLocations}</h3>{roots.map(r=><div className="root-row" key={r.id}><Folder/><div><b>{r.name}</b><span>{r.path} · {t.includesSubfolders}</span></div><ShieldCheck/><button className="root-remove" onClick={()=>removeRoot(r)}><X/></button></div>)}<button className="secondary" onClick={addRoot}><FolderPlus/>{t.addLocation}</button></div></div></div>}

function DownloadCenter({t,jobs,onClose,onControl,onCancel,onRetry,onRemove}:{t:Strings;jobs:Job[];onClose:()=>void;onControl:(j:Job)=>void;onCancel:(j:Job)=>void;onRetry:(j:Job)=>void;onRemove:(id:number)=>void}){const[filter,setFilter]=useState<'all'|'active'|'done'|'problem'>('all');const list=jobs.filter(j=>filter==='all'?true:filter==='active'?(j.status==='downloading'||j.status==='paused'):filter==='done'?j.status==='done':(j.status==='error'||j.status==='canceled'));return <div className="overlay"><div className="modal download-center"><div className="modal-head"><div><h2>{t.downloadCenter}</h2><span>{jobs.length} {t.items}</span></div><button onClick={onClose}><X/></button></div><div className="download-filters">{[['all',t.all],['active',t.active],['done',t.completed],['problem',t.problems]].map(([key,label])=><button key={key} className={filter===key?'picked':''} onClick={()=>setFilter(key as typeof filter)}>{label}</button>)}</div><div className="center-list">{list.length===0?<div className="empty-jobs">{t.noCategory}</div>:list.map(j=><div className="center-job" key={j.id}><div className="job-icon"><Film/></div><div className="job-info"><b>{j.name}</b><span>{j.type} · {j.destination}</span><div className="progress"><i style={{width:j.progress+'%'}}/></div><small>{j.progress}% · {j.speed||'—'} · {j.eta||'—'}</small></div><div className="center-actions">{(j.status==='downloading'||j.status==='paused')&&<button onClick={()=>onControl(j)}>{j.status==='paused'?<Play/>:<Pause/>}</button>}{(j.status==='error'||j.status==='canceled')&&<button onClick={()=>onRetry(j)}><RefreshCw/></button>}{(j.status==='downloading'||j.status==='paused')&&<button onClick={()=>onCancel(j)}><X/></button>}{(j.status==='done'||j.status==='error'||j.status==='canceled')&&<button onClick={()=>onRemove(j.id)}><Trash2/></button>}</div></div>)}</div></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
