import React,{useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Folder,FolderPlus,Download,Settings,Search,Grid2X2,List,Plus,ChevronRight,Home,Music,Film,Image,HardDrive,ShieldCheck,Pause,Play,X,Check,Globe2,LockKeyhole,MoreVertical,RefreshCw}from'lucide-react';import'./styles.css';

type Root={id:string;name:string;path:string};type FileItem={name:string;kind:'folder'|'file';type?:string;size?:string;thumb?:string};type Job={id:number;name:string;type:string;progress:number;speed:string;eta:string;status:'downloading'|'done'|'paused'};

const roots:Root[]=[{id:'media',name:'Media',path:'D:\\Media'},{id:'downloads',name:'Downloads',path:'C:\\Users\\User\\Downloads'}];
const files:FileItem[]=[{name:'Movies',kind:'folder'},{name:'Music',kind:'folder'},{name:'Pictures',kind:'folder'},{name:'Projects',kind:'folder'},{name:'Interstellar.mp4',kind:'file',type:'1080p • MP4',size:'1.42 GB'},{name:'Inception.mp4',kind:'file',type:'1080p • MP4',size:'1.12 GB'},{name:'Dune.mp4',kind:'file',type:'1080p • MP4',size:'1.34 GB'},{name:'Imagine Dragons - Believer.mp3',kind:'file',type:'MP3',size:'8.2 MB'}];

function App(){const[active,setActive]=useState('media');const[path,setPath]=useState<string[]>(['Media']);const[view,setView]=useState<'grid'|'list'>('grid');const[add,setAdd]=useState(false);const[settings,setSettings]=useState(false);const[jobs,setJobs]=useState<Job[]>([{id:1,name:'Rick Astley - Never Gonna Give You Up.mp4',type:'1080p • MP4',progress:67,speed:'12.3 MB/s',eta:'00:00:54',status:'downloading'},{id:2,name:'Interstellar.mp4',type:'1080p • MP4',progress:34,speed:'8.7 MB/s',eta:'01:32:21',status:'downloading'},{id:3,name:'Imagine Dragons - Believer.mp3',type:'MP3',progress:100,speed:'',eta:'',status:'done'}]);const current=roots.find(r=>r.id===active)!;const breadcrumb=useMemo(()=>path.join(' › '),[path]);
return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">▶</div><div><b>DownTrack</b><span>Media Workspace</span></div></div><div className="section-label">מיקומים</div><button className="nav active"><Home/> Home</button>{roots.map(r=><button key={r.id} className={'nav '+(active===r.id?'selected':'')} onClick={()=>{setActive(r.id);setPath([r.name])}}><Folder/> {r.name}</button>)}<button className="nav"><Download/> הורדות <em>{jobs.filter(j=>j.status==='downloading').length}</em></button><div className="side-spacer"/><button className="nav accent" onClick={()=>setAdd(true)}><Plus/> הוספת מדיה</button><button className="nav" onClick={()=>setSettings(true)}><Settings/> הגדרות</button><div className="secure"><ShieldCheck/><div><b>Workspace מוגן</b><span>גישה רק לתיקיות מאושרות</span></div></div></aside>
<main className="main"><header><div className="crumbs"><button onClick={()=>setPath([current.name])}><Home size={16}/></button><ChevronRight size={15}/><span>{breadcrumb}</span></div><div className="search"><Search size={17}/><input placeholder="חיפוש בקבצים..."/></div><div className="toolbar"><button onClick={()=>setView('grid')} className={view==='grid'?'on':''}><Grid2X2 size={18}/></button><button onClick={()=>setView('list')} className={view==='list'?'on':''}><List size={18}/></button><button><RefreshCw size={18}/></button></div></header>
<section className="content"><div className="title-row"><div><h1>{current.name}</h1><p>{current.path} · כל תיקיות המשנה מורשות</p></div><button className="primary" onClick={()=>setAdd(true)}><Plus size={18}/> הוספת מדיה</button></div>
<div className={view==='grid'?'file-grid':'file-list'}>{files.map((f,i)=><article key={f.name} className="file-card">{f.kind==='folder'?<><div className="folder-icon"><Folder/></div><b>{f.name}</b><span>תיקייה</span></>:<><div className="thumb"><div className="media-symbol">{f.type==='MP3'?<Music/>:<Film/>}</div></div><b title={f.name}>{f.name}</b><span>{f.type} · {f.size}</span><button className="more"><MoreVertical size={17}/></button></>}</article>)}</div></section>
<div className="downloads-panel"><div className="panel-head"><div><b>הורדות פעילות</b><span>{jobs.filter(j=>j.status==='downloading').length} פעילות</span></div><button>הצג הכל <ChevronRight size={15}/></button></div><div className="job-row">{jobs.slice(0,2).map(j=><div className="job" key={j.id}><div className="job-icon"><Film/></div><div className="job-info"><b>{j.name}</b><span>{j.type}</span><div className="progress"><i style={{width:j.progress+'%'}}/></div><small>{j.progress}% · {j.speed} · {j.eta}</small></div><button>{j.status==='paused'?<Play/>:<Pause/>}</button><button><X/></button></div>)}</div></div>
</main>{add&&<AddMedia onClose={()=>setAdd(false)} target={current.path}/>} {settings&&<SettingsModal onClose={()=>setSettings(false)}/>}</div>}

function AddMedia({onClose,target}:{onClose:()=>void;target:string}){const[quality,setQuality]=useState('1080p (Full HD)');const[format,setFormat]=useState('MP4');const[name,setName]=useState('Rick Astley - Never Gonna Give You Up');return <div className="overlay"><div className="modal add-modal"><div className="modal-head"><div><h2>הוספת מדיה</h2><span>הורדה תישמר ישירות בתיקייה הנוכחית</span></div><button onClick={onClose}><X/></button></div><label>קישור<input autoFocus placeholder="הדבק קישור למדיה..."/></label><div className="preview"><div className="preview-img"><Film/></div><div><b>Rick Astley - Never Gonna Give You Up</b><span>4:12 · YouTube</span></div><Check/></div><label>איכות<select value={quality} onChange={e=>setQuality(e.target.value)}><option>2160p (4K)</option><option>1440p (2K)</option><option>1080p (Full HD)</option><option>720p (HD)</option><option>480p</option></select></label><div className="formats"><label>פורמט</label><div><button className={format==='MP4'?'picked':''} onClick={()=>setFormat('MP4')}>MP4</button><button className={format==='MKV'?'picked':''} onClick={()=>setFormat('MKV')}>MKV</button><button className={format==='MP3'?'picked':''} onClick={()=>setFormat('MP3')}>MP3</button></div></div><label>שם הקובץ<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="destination"><Folder size={18}/><div><span>יישמר בתוך</span><b>{target}</b></div><Check size={17}/></div><button className="primary wide" onClick={onClose}><Download size={18}/> הוסף להורדות</button></div></div>}

function SettingsModal({onClose}:{onClose:()=>void}){return <div className="overlay"><div className="modal settings-modal"><div className="modal-head"><div><h2>הגדרות</h2><span>שליטה מלאה ב־DownTrack</span></div><button onClick={onClose}><X/></button></div><div className="settings-grid"><div className="setting active"><Globe2/><div><b>שפה</b><span>עברית · 20 שפות זמינות</span></div></div><div className="setting"><LockKeyhole/><div><b>פרטיות ואבטחה</b><span>Roots מורשים בלבד</span></div></div><div className="setting"><Download/><div><b>הורדות</b><span>תורים, מהירות וחיבורים</span></div></div><div className="setting"><HardDrive/><div><b>אחסון</b><span>מיקומי שמירה וניקוי</span></div></div></div><div className="roots"><h3>מיקומים מורשים</h3>{roots.map(r=><div className="root-row" key={r.id}><Folder/><div><b>{r.name}</b><span>{r.path} · כולל כל תיקיות המשנה</span></div><ShieldCheck/></div>)}<button className="secondary"><FolderPlus size={17}/> הוסף מיקום</button></div></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);